### ISSUE TITLE
mariana-color-theme.json 显示错误

### ISSUE THREAD

**Issue by muddyneil** [mightbesimon/vscode-mariana#18]
单泉，你好！昨天才发现这个主题，我认为最接近完美的主题，相见恨晚！发现有个小问题，mariana-color-theme.json 文件好像格式丢失，文字都挤到一块了。
![Screenshot 2023-12-11 181823](https://github.com/mightbesimon/vscode-mariana/assets/35959703/c0d099ec-260b-4c8e-a4d8-e72942ef1d90)

**Comment by mightbesimon** [comment]
Hi muddyneil, many thanks for your supportive compliment! Regarding your question, are you referring to missing newline and whitespace characters? These characters are removed during compilation to reduce the final file size by saving character bytes. In the publish action workflow, only the compiled JSON is uploaded into the final package. Meanwhile, the reference JSON retains newline and whitespace characters to remain readable during development without uploading.

My Chinese is good but limited. I can respond better in English or German. For the time being, I will mark this issue as resolved. Please feel free to add further comments if you have more questions 🙂

嗨 muddyneil，非常感谢你的支持赞美！ 关于你的问题，你指的是缺少换行符和空格字符吗？ 这些字符在编译期间被删除，以通过节省字符字节来减少最终文件的大小。 在发布操作工作流程中，仅将编译后的 JSON 上传到最终包中。 同时，参考 JSON 保留了换行符和空格字符，以便在开发过程中保持可读性而无需上传。

我的中文很好但有限。 我可以用英语或德语更好地回答。 目前，我会将这个问题标记为已解决。 如果你有更多问题，请随时添加进一步的评论 🙂

**Comment by muddyneil** [comment]
> Hi muddyneil, many thanks for your supportive compliment! Regarding your question, are you referring to missing newline and whitespace characters? These characters are removed during compilation to reduce the final file size by saving character bytes. In the publish action workflow, only the compiled JSON is uploaded into the final package. Meanwhile, the reference JSON retains newline and whitespace characters to remain readable during development without uploading.
> 
> My Chinese is good but limited. I can respond better in English or German. For the time being, I will mark this issue as resolved. Please feel free to add further comments if you have more questions 🙂
> 
> 嗨 muddyneil，非常感谢你的支持赞美！ 关于你的问题，你指的是缺少换行符和空格字符吗？ 这些字符在编译期间被删除，以通过节省字符字节来减少最终文件的大小。 在发布操作工作流程中，仅将编译后的 JSON 上传到最终包中。 同时，参考 JSON 保留了换行符和空格字符，以便在开发过程中保持可读性而无需上传。
> 
> 我的中文很好但有限。 我可以用英语或德语更好地回答。 目前，我会将这个问题标记为已解决。 如果你有更多问题，请随时添加进一步的评论 🙂

很开心这么快就有回复了！
你的中文非常好，还有个很漂亮的中文名。
你的理解很对。我昨天查看JSON，发现缺少换行符和空格字符，还以为 fileformat 不一致的原因，现在我明白了。
