### ISSUE TITLE
yaml file color for key name

### ISSUE THREAD

**Issue by cloud-66** [mightbesimon/vscode-mariana#5]
first sublime - second vscode
for me  orange color for variables is good maybee it depends on additional extension which recognize varriable
but red key name looks too agressive,
dark green color in sublime more neutral and pleasant
![image](https://user-images.githubusercontent.com/41143306/212142150-a798276e-180f-49cb-a43d-3a12201251fb.png)

![image](https://user-images.githubusercontent.com/41143306/212142852-e752b106-6ca6-4f07-8b85-8d30a6c45d66.png)

**Comment by guillemap** [comment]
Fixed in https://github.com/mightbesimon/vscode-mariana/pull/2

**Comment by mightbesimon** [comment]
hi, thanks for submitting this issue. Which vscode version are you one? my yml files match sublime tests for me. so I'm wondering if this could just be a difference in yml symbol parsing by different vscode versions.

**Comment by mightbesimon** [comment]
<img width="526" alt="Screen Shot 2023-01-27 at 11 19 53 AM" src="https://user-images.githubusercontent.com/60593422/214963716-85ae3c92-2d8d-4940-a5ea-1ade213ecdc6.png">

**Comment by guillemap** [comment]
Mine looked like @cloud-66 before https://github.com/mightbesimon/vscode-mariana/pull/4

**Comment by cloud-66** [comment]
Yeah,  it's been fixed. Thank you
